# Generated by Django 5.0.2 on 2024-03-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='media/profile-icon.png', upload_to='profile_images'),
        ),
    ]
